import esbuild from "esbuild";
import process from "node:process";
import { builtinModules } from "node:module";
import { copyFileSync, existsSync, mkdirSync, readFileSync } from "node:fs";
import { homedir } from "node:os";
import { join, resolve } from "node:path";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
*/
`;

const prod = process.argv[2] === "production";

function expandTilde(value) {
	return value.startsWith("~/") ? join(homedir(), value.slice(2)) : value;
}

function getCopyDestinations() {
	const localFile = resolve(process.cwd(), ".copy-files.local");
	if (!existsSync(localFile)) return [];

	return readFileSync(localFile, "utf8")
		.split("\n")
		.map((line) => line.trim())
		.filter((line) => line.length > 0 && !line.startsWith("#"))
		.map(expandTilde);
}

const copyToVaultPlugin = {
	name: "copy-to-vault",
	setup(build) {
		const destinations = getCopyDestinations();
		if (destinations.length === 0) return;

		build.onEnd((result) => {
			if (result.errors.length > 0) return;

			for (const dest of destinations) {
				mkdirSync(dest, { recursive: true });
				for (const file of ["main.js", "styles.css", "manifest.json"]) {
					const source = resolve(process.cwd(), file);
					if (existsSync(source)) {
						copyFileSync(source, join(dest, file));
					}
				}
				console.log(`Copied to ${dest}`);
			}
		});
	},
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/*",
		...builtinModules,
		...builtinModules.map((moduleName) => `node:${moduleName}`),
	],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
	plugins: prod ? [] : [copyToVaultPlugin],
});

if (prod) {
	await context.rebuild();
	process.exit(0);
}

await context.watch();
